; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_lightstrip

[env:esp32_net_node]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<gateway_net_node.cpp> +<HueMixLink.h>
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	thomasfredericks/Bounce2@^2.72
lib_compat_mode = strict

[env:esp32_radio_node]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<gateway_radio_node.cpp> +<HueMixLink.h>
lib_compat_mode = strict

[env:esp32_normal_button]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<normal_button.cpp> +<HueMixLink.h>
lib_deps = 
	thomasfredericks/Bounce2@^2.72
lib_compat_mode = strict

[env:esp32_lightstrip]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
lib_deps = 
	fastled/FastLED@^3.10.3
lib_compat_mode = strict

[env:esp32_remote_button]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<remote_button.cpp> +<HueMixLink.h>
lib_deps = 
	thomasfredericks/Bounce2@^2.72
lib_compat_mode = strict

[env:esp8266_normal_button]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = +<normal_button.cpp> +<HueMixLink.h>
lib_deps = 
	thomasfredericks/Bounce2@^2.72
	vshymanskyy/Preferences@^2.2.2

[env:esp8266_lightstrip]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
lib_deps = 
	fastled/FastLED@^3.10.3
	vshymanskyy/Preferences@^2.2.2
