; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = .pio/cache
default_envs =
    esp32_net_node
    esp32_radio_node
    esp32_normal_button
    esp8266_normal_button
    esp32_remote_button
    esp32_motion_sensor
    esp32_lightstrip_1
	esp8266_lightstrip_2
    esp32_lightstrip_3
	esp8266_lightstrip_4
	esp32_lightstrip_5
	esp8266_lightstrip_6

[env:esp32_net_node]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<gateway_net_node.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.8.0\"
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	thomasfredericks/Bounce2@^2.72
lib_compat_mode = strict

[env:esp32_radio_node]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<gateway_radio_node.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.8.1\"
lib_compat_mode = strict

[env:esp32_normal_button]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<normal_button.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.6\"
lib_deps = 
	thomasfredericks/Bounce2@^2.72
lib_compat_mode = strict

[env:esp8266_normal_button]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = +<normal_button.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.7\"
lib_deps = 
	thomasfredericks/Bounce2@^2.72
	vshymanskyy/Preferences@^2.2.2

[env:esp32_remote_button]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<remote_button.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.8.1\"
lib_deps = 
	thomasfredericks/Bounce2@^2.72
lib_compat_mode = strict

[env:esp32_motion_sensor]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<motion_sensor.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.1.7\"
lib_compat_mode = strict


[env:esp32_lightstrip_1]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.6\"
	-DLIGHTSTRIP_MODEL=1
lib_deps = 
	fastled/FastLED@^3.10.3
lib_compat_mode = strict

[env:esp8266_lightstrip_2]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.6\"
	-DLIGHTSTRIP_MODEL=2
lib_deps = 
	fastled/FastLED@^3.10.3
	vshymanskyy/Preferences@^2.2.2

[env:esp32_lightstrip_3]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.6\"
	-DLIGHTSTRIP_MODEL=3
lib_deps = 
	fastled/FastLED@^3.10.3
lib_compat_mode = strict

[env:esp8266_lightstrip_4]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.6\"
	-DLIGHTSTRIP_MODEL=4
lib_deps = 
	fastled/FastLED@^3.10.3
	vshymanskyy/Preferences@^2.2.2

[env:esp32_lightstrip_5]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.6\"
	-DLIGHTSTRIP_MODEL=5
lib_deps = 
	fastled/FastLED@^3.10.3
lib_compat_mode = strict

[env:esp8266_lightstrip_6]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = +<lightstrip.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"3.7.6\"
	-DLIGHTSTRIP_MODEL=6
lib_deps = 
	fastled/FastLED@^3.10.3
	vshymanskyy/Preferences@^2.2.2
